services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -d ${POSTGRES_DEFAULT_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  lake_seed:
    build: ./services/lake_seed
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      STORAGE_ENDPOINT_URL: ${STORAGE_ENDPOINT_URL}
    depends_on:
      - minio

  # PLATFORM (global): schemas + metadata tables
  platform_bootstrap:
    build: ./services/db_bootstrap
    entrypoint: ["/app/run.sh"]
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
    volumes:
      - ./infra/postgres/00_platform:/sql:ro
    depends_on:
      - postgres

  # DATASET (iris): create raw/staging tables only
  iris_bootstrap:
    build: ./services/db_bootstrap
    entrypoint: ["/app/run.sh"]
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
    volumes:
      - ./infra/postgres/10_datasets/iris/tables:/sql:ro
    depends_on:
      - postgres

  warehouse_loader:
    build: ./services/warehouse_loader
    environment:
      # MinIO
      STORAGE_ENDPOINT_URL: ${STORAGE_ENDPOINT_URL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      # Postgres (Warehouse)
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}

      # Dataset (optional)
      DATASET_BUCKET: datasets
      DATASET_KEY: iris/v1/iris.csv
      DATASET_NAME: iris
      DATASET_VERSION: v1
    depends_on:
      - postgres
      - minio

  # DATASET (iris): transform raw -> staging
  iris_transform:
    build: ./services/db_bootstrap
    entrypoint: ["/app/run.sh"]
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
    volumes:
      - ./infra/postgres/10_datasets/iris/transforms:/sql:ro
    depends_on:
      - postgres
      - iris_bootstrap
      - warehouse_loader


volumes:
  postgres_data:
  minio_data:
